// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var diaperOptions = [
  "Mixed",
  "Wet",
  "Dirty"
];

var feedingOptions = [
  "Nursing",
  "Bottle"
];

export {
  diaperOptions ,
  feedingOptions ,
  
}
/* No side effect */
