// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Row from "react-bootstrap/Row";

var Row$1 = {};

function SignOut(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement("h1", undefined, "You have successfully signed out!")
                }), React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement("p", undefined, "Thank you for using our app")
                }));
}

var make = SignOut;

var $$default = SignOut;

export {
  Row$1 as Row,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
