// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Axios from "../../node_modules/bs-axios/src/axios.js";
import * as Axios$1 from "axios";
import * as ApiConstants$MyBabyApp from "../constants/ApiConstants.bs.js";
import * as CommonHeaders$MyBabyApp from "./CommonHeaders.bs.js";

function createBaby(token, babyInput) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.post(ApiConstants$MyBabyApp.host + "/babies", babyInput, {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function getBabies(token, userId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.get(ApiConstants$MyBabyApp.host + ("users/" + (userId + "/babies")), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function deleteBaby(token, babyId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.delete(ApiConstants$MyBabyApp.host + ("babies/" + babyId), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function editBaby(token, babyId, babyInput) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.patch(ApiConstants$MyBabyApp.host + ("/babies/" + babyId), babyInput, {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function getBabyWithEvents(token, babyId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.get(ApiConstants$MyBabyApp.host + ("babies/" + babyId), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

export {
  createBaby ,
  getBabies ,
  deleteBaby ,
  editBaby ,
  getBabyWithEvents ,
  
}
/* axios Not a pure module */
