// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function configureTokenHeaders(token) {
  return {
          Authorization: "Bearer " + token
        };
}

export {
  configureTokenHeaders ,
  
}
/* No side effect */
