// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Axios from "../../node_modules/bs-axios/src/axios.js";
import * as Axios$1 from "axios";
import * as ApiConstants$MyBabyApp from "../constants/ApiConstants.bs.js";
import * as CommonHeaders$MyBabyApp from "./CommonHeaders.bs.js";

function createDiapersEvent(token, diaperInput) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.post(ApiConstants$MyBabyApp.host + "diapers", diaperInput, {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function getDiapers(token, babyId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.get(ApiConstants$MyBabyApp.host + ("babies/" + (babyId + "/diapers")), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function deleteDiapers(token, diaperId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.delete(ApiConstants$MyBabyApp.host + ("diapers/" + diaperId), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function editDiapers(token, diaperId, diaperInput) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.patch(ApiConstants$MyBabyApp.host + ("diapers/" + diaperId), diaperInput, {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

export {
  createDiapersEvent ,
  getDiapers ,
  deleteDiapers ,
  editDiapers ,
  
}
/* axios Not a pure module */
