// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Axios from "../../node_modules/bs-axios/src/axios.js";
import * as Axios$1 from "axios";
import * as ApiConstants$MyBabyApp from "../constants/ApiConstants.bs.js";
import * as CommonHeaders$MyBabyApp from "./CommonHeaders.bs.js";

function createFeedingsEvent(token, feedingInput) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.post(ApiConstants$MyBabyApp.host + "feedings", feedingInput, {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function getFeedings(token, babyId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.get(ApiConstants$MyBabyApp.host + ("babies/" + (babyId + "/feedings")), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function deleteFeedings(token, feedingId) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.delete(ApiConstants$MyBabyApp.host + ("feedings/" + feedingId), {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

function editFeedings(token, feedingId, feedingInput) {
  var headerObject = CommonHeaders$MyBabyApp.configureTokenHeaders(token);
  var headers = Axios.$$Headers.fromObj(headerObject);
  return Axios$1.patch(ApiConstants$MyBabyApp.host + ("feedings/" + feedingId), feedingInput, {
                  headers: headers
                }).then(function (response) {
                return Promise.resolve(response.data);
              }).catch(function (error) {
              return Promise.resolve(error.response.data);
            });
}

export {
  createFeedingsEvent ,
  getFeedings ,
  deleteFeedings ,
  editFeedings ,
  
}
/* axios Not a pure module */
