// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$String from "../../node_modules/bs-platform/lib/es6/string.js";
import * as Caml_option from "../../node_modules/bs-platform/lib/es6/caml_option.js";

function isValidPassword(password) {
  return password.length >= 8;
}

var emailRegex = /^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,6})*$/;

function isValidEmail(email) {
  return Caml_option.null_to_opt(email.match(emailRegex)) !== undefined;
}

function isValidSignIn(email, password) {
  if (isValidEmail(email)) {
    return password.length >= 8;
  } else {
    return false;
  }
}

function passwordMatches(password, confirmPassword) {
  return $$String.compare(password, confirmPassword) === 0;
}

function isValidRegistration(email, password, confirmPassword) {
  if (isValidSignIn(email, password)) {
    return passwordMatches(password, confirmPassword);
  } else {
    return false;
  }
}

export {
  isValidPassword ,
  emailRegex ,
  isValidEmail ,
  isValidSignIn ,
  passwordMatches ,
  isValidRegistration ,
  
}
/* No side effect */
