// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$String from "../../node_modules/bs-platform/lib/es6/string.js";

function hasReachedChildLimit(babies) {
  return babies.length >= 4;
}

function formatDateString(dateString) {
  return $$String.sub(dateString, 0, 10);
}

export {
  hasReachedChildLimit ,
  formatDateString ,
  
}
/* No side effect */
