// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function isNotEmpty(field) {
  return field !== "";
}

function textMatches(text1, text2) {
  return text1 === text2;
}

export {
  isNotEmpty ,
  textMatches ,
  
}
/* No side effect */
