// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$String from "../../node_modules/bs-platform/lib/es6/string.js";

function isEmptyString(string) {
  return string === "";
}

function doStringsMatch(string1, string2) {
  return $$String.compare(string1, string2) === 0;
}

export {
  isEmptyString ,
  doStringsMatch ,
  
}
/* No side effect */
