// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Row from "react-bootstrap/Row";
import * as Container from "react-bootstrap/Container";

var Container$1 = {};

var Row$1 = {};

function ErrorPage(Props) {
  return React.createElement(Container.default, {
              children: null
            }, React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement("h1", {
                        className: "text-center"
                      }, "Woops! Something went wrong")
                }), React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement("p", undefined, "Try signing in again to use our application.")
                }));
}

var make = ErrorPage;

var $$default = ErrorPage;

export {
  Container$1 as Container,
  Row$1 as Row,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
