// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "react-bootstrap/Button";

var Button$1 = {};

function SignUpSuccess(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Great success!"), React.createElement("p", undefined, "Login to get started"), React.createElement(Button.default, {
                  href: "/login",
                  children: "Login Now"
                }));
}

var make = SignUpSuccess;

var $$default = SignUpSuccess;

export {
  Button$1 as Button,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
