// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Row from "react-bootstrap/Row";
import * as Button from "react-bootstrap/Button";

var Button$1 = {};

var Row$1 = {};

function SignUpSuccess(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement("h1", undefined, "Great success!")
                }), React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement("p", undefined, "Login to your new account to get started")
                }), React.createElement(Row.default, {
                  className: "justify-content-center",
                  children: React.createElement(Button.default, {
                        href: "/login",
                        children: "Login Now"
                      })
                }));
}

var make = SignUpSuccess;

var $$default = SignUpSuccess;

export {
  Button$1 as Button,
  Row$1 as Row,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
